// 배송 상태 상수
export const SHIPPING_STATUS = {
  SHIPPING: 'shipping',
  DELIVERED: 'delivered',
  RETURNED: 'returned',
  CANCELLED: 'cancelled',
  ERROR: 'error',
} as const

export const SHIPPING_STATUS_LABELS = {
  [SHIPPING_STATUS.SHIPPING]: '배송중',
  [SHIPPING_STATUS.DELIVERED]: '배송완료',
  [SHIPPING_STATUS.RETURNED]: '반품',
  [SHIPPING_STATUS.CANCELLED]: '취소',
  [SHIPPING_STATUS.ERROR]: '오류',
} as const

// 정렬 옵션
export const SORT_OPTIONS = [
  { value: 'date_desc', label: '주문일시 (최신순)' },
  { value: 'date_asc', label: '주문일시 (오래된순)' },
  { value: 'order_id_desc', label: '주문번호 (내림차순)' },
  { value: 'order_id_asc', label: '주문번호 (오름차순)' },
] as const

// 페이지네이션 기본값
export const PAGINATION = {
  DEFAULT_LIMIT: 50,
  MAX_LIMIT: 100,
  DEFAULT_OFFSET: 0,
} as const

// 날짜 형식
export const DATE_FORMATS = {
  DISPLAY: 'yyyy-MM-dd HH:mm',
  DATE_ONLY: 'yyyy-MM-dd',
  TIME_ONLY: 'HH:mm',
  ISO: "yyyy-MM-dd'T'HH:mm:ss.SSSxxx",
} as const

// API 엔드포인트
export const API_ENDPOINTS = {
  OAUTH: {
    INSTALL: '/oauth/install',
    STATUS: '/oauth/status',
    CALLBACK: '/oauth/callback',
  },
  ORDERS: {
    LIST: '/api/orders',
    DETAIL: (id: string) => `/api/orders/${id}`,
    SHIPMENTS: (id: string) => `/api/orders/${id}/shipments`,
    STATS: '/api/orders/stats/summary',
  },
  WEBHOOK: {
    LOGIVIEW: '/webhook/logiview',
    TEST: '/webhook/test',
    STATUS: '/webhook/status',
  },
  HEALTH: '/health',
} as const

// 로컬 스토리지 키
export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'access_token',
  REFRESH_TOKEN: 'refresh_token',
  USER_PREFERENCES: 'user_preferences',
  THEME: 'theme',
  ADMIN_SESSION: 'admin_session',
  SAVED_MALLS: 'saved_malls',
  CURRENT_MALL: 'current_mall',
} as const

// 테마 색상
export const THEME_COLORS = {
  PRIMARY: '#3b82f6',
  SUCCESS: '#22c55e',
  WARNING: '#f59e0b',
  DANGER: '#ef4444',
  INFO: '#06b6d4',
} as const

// 반응형 브레이크포인트
export const BREAKPOINTS = {
  SM: 640,
  MD: 768,
  LG: 1024,
  XL: 1280,
  '2XL': 1536,
} as const

// 애니메이션 지속시간
export const ANIMATION_DURATION = {
  FAST: 150,
  NORMAL: 300,
  SLOW: 500,
} as const

// 토스트 메시지 지속시간
export const TOAST_DURATION = {
  SUCCESS: 3000,
  ERROR: 5000,
  INFO: 4000,
  WARNING: 4000,
} as const

// 배송업체 목록 (카페24 배송업체 코드)
export const SHIPPING_COMPANIES = [
  { code: '0002', name: '건영택배' },
  { code: '0004', name: '로젠택배' },
  { code: '0005', name: '삼성택배(HTH)' },
  { code: '0006', name: 'CJ대한통운' },
  { code: '0007', name: '아주택배' },
  { code: '0009', name: '오렌지택배' },
  { code: '0010', name: '오세기고구려' },
  { code: '0011', name: '용마로지스' },
  { code: '0012', name: '우체국택배' },
  { code: '0013', name: '우체국(등기,소포 우편)' },
  { code: '0014', name: '이젠택배' },
  { code: '0015', name: '이클라인' },
  { code: '0016', name: '일양택배' },
  { code: '0017', name: '트라넷' },
  { code: '0018', name: '한진택배' },
  { code: '0019', name: '롯데택배' },
  { code: '0021', name: 'KGB특급택배' },
  { code: '0022', name: 'KGB택배' },
  { code: '0023', name: 'KL-Net 택배' },
  { code: '0024', name: 'LOEX 택배' },
  { code: '0025', name: '일반택배' },
  { code: '0026', name: 'DHL' },
  { code: '0027', name: 'FedEx' },
  { code: '0028', name: 'UPS' },
  { code: '0029', name: '국제특급 EMS' },
  { code: '0030', name: '국제특급 EMS 프리미엄' },
  { code: '0031', name: '국제항공소포' },
  { code: '0032', name: '국제선편소포' },
  { code: '0033', name: '선편소형포장물' },
  { code: '0034', name: '항공소형포장물' },
  { code: '0035', name: 'SAL소포' },
  { code: '0036', name: '벨익스프레스' },
  { code: '0037', name: '우리택배' },
  { code: '0038', name: '코덱스택배' },
  { code: '0039', name: '경동택배' },
  { code: '0040', name: '스피디익스프레스' },
  { code: '0041', name: '고구려택배' },
  { code: '0042', name: '양양택배' },
  { code: '0043', name: '대신택배' },
  { code: '0044', name: '천일택배' },
  { code: '0045', name: '하이브랜로지스' },
  { code: '0046', name: '호남택배' },
  { code: '0047', name: '동서택배' },
  { code: '0048', name: '한국택배' },
  { code: '0049', name: '이트랜스택배' },
  { code: '0050', name: '이패밀리' },
  { code: '0051', name: '하나로택배' },
  { code: '0052', name: 'WPX택배' },
  { code: '0053', name: '메일렉스코리아' },
  { code: '0055', name: 'SEDEX(신세계)' },
  { code: '0056', name: 'SC로지스' },
  { code: '0057', name: '굿모닝택배' },
  { code: '0058', name: '정안CLS' },
  { code: '0059', name: 'AirboyExpress' },
  { code: '0060', name: '퀵퀵닷컴' },
  { code: '0061', name: '이노지스' },
  { code: '0062', name: 'GS Postbox(CVSnet)' },
  { code: '0063', name: '위즈와' },
  { code: '0064', name: '포시즌익스프레스' },
  { code: '0065', name: '인로스' },
  { code: '0066', name: 'USX 국제특송' },
  { code: '0067', name: '한진화물' },
  { code: '0068', name: 'ACI Express' },
  { code: '0069', name: '바익스' },
  { code: '0070', name: '인티박스' },
  { code: '0071', name: 'USPS' },
  { code: '0072', name: 'First Air Express' },
  { code: '0073', name: 'hddt(HDL)' },
  { code: '0074', name: 'GTX 로지스' },
  { code: '0075', name: 'TNT 익스프레스' },
  { code: '0076', name: 'GSM' },
  { code: '0077', name: '합동택배' },
  { code: '0078', name: 'GPS lgx' },
  { code: '0079', name: '롯데글로벌로지스' },
  { code: '0080', name: 'MIT EXPRESS CO., LTD' },
  { code: '0081', name: 'FASTBOX' },
  { code: '0082', name: 'CAINIAO' },
  { code: '0083', name: '사가와 익스프레스' },
  { code: '0084', name: '야마토 운송' },
  { code: '0085', name: '순평(SF)' },
  { code: '0086', name: 'LX판토스' },
  { code: '0087', name: 'RINCOS' },
  { code: '0088', name: '야마토택배' },
  { code: '0089', name: 'STO Express' },
  { code: '0090', name: '한진 Fedex' },
  { code: '0091', name: '사가와택배(飛脚宅配便)' },
  { code: '0093', name: '중통택배' },
  { code: '0094', name: 'OCS' },
  { code: '0095', name: 'WEX24(SMART POST)' },
  { code: '0096', name: '야마토(黑貓宅急便)' },
  { code: '0098', name: 'Japan Post Service (EMS)' },
  { code: '0099', name: '고쿠사이 익스프레스' },
  { code: '0107', name: 'Seino Transportation' },
  { code: '0213', name: 'SLX택배' },
  { code: '0214', name: '한의사랑' },
  { code: '0215', name: '한덱스' },
  { code: '0216', name: '굿투럭' },
  { code: '0217', name: 'KGL네트웍스' },
  { code: '0218', name: 'I-Parcel' },
  { code: '0219', name: 'ACE Express' },
  { code: '0220', name: '성원글로벌' },
  { code: '0221', name: '스마트로지스' },
  { code: '0222', name: '큐익스프레스' },
  { code: '0223', name: '워펙스' },
  { code: '0224', name: '퍼레버택배' },
  { code: '0225', name: '우리동네택배' },
  { code: '0226', name: '자이언트' },
  { code: '0227', name: '씨웨이' },
  { code: '0228', name: '홈이노베이션' },
  { code: '0229', name: '브리지로지스' },
  { code: '0230', name: '시알로지텍' },
  { code: '0231', name: '두발히어로' },
  { code: '0232', name: '로지스파트너' },
  { code: '0233', name: '카카오 T 당일배송' },
  { code: '0234', name: '컬리넥스트마일' },
  { code: '0235', name: '투데이' },
  { code: '0237', name: '핑퐁' },
  { code: '0238', name: 'ARGO' },
  { code: '0239', name: 'JoomLogistics' },
  { code: '0240', name: '팀프레시' },
  { code: '0241', name: '우리한방택배' },
  { code: '0242', name: '용성종합물류' },
  { code: '0243', name: '프레딧(HY)' },
  { code: '0244', name: '딜리박스' },
  { code: '0245', name: 'ENVYCUBE' },
  { code: '0246', name: 'ENVYCUBE Light' },
  { code: '0247', name: '홈픽' },
  { code: '0248', name: '쉽터' },
  { code: '0249', name: '케이티 익스프레스' },
  { code: '0250', name: '홈픽 오늘도착' },
  { code: '0251', name: 'Qxpress economy' },
  { code: '0252', name: 'EFS' },
  { code: '0253', name: '델레오' },
  { code: '0254', name: 'CJ대한통운 CBE' },
  { code: '1003', name: 'CATS YTO express logistics' },
  { code: '1070', name: 'FASTBOX(연동)' },
  { code: '1071', name: 'Fastbox Mail' },
  { code: '1072', name: 'Fastbox Economy' },
  { code: '1073', name: 'Fastbox Standard' },
  { code: '1074', name: 'Fastbox Premium' },
  { code: '1075', name: '세방택배' },
  { code: '1076', name: '농협택배' },
  { code: '1077', name: 'FamilyMart Pickup' },
  { code: '1078', name: 'CU편의점택배' },
  { code: '1079', name: '도도플렉스당일도착' },
  { code: '1080', name: '글로벌 해상 특송' },
  { code: '1081', name: 'Pantos' },
  { code: '1082', name: 'Qxpress' },
  { code: '1083', name: 'Qprime' },
  { code: '1084', name: 'GSI Express' },
  { code: '1088', name: '로지스밸리(logisvalley)' },
  { code: '9996', name: '오늘도착(원더스)' },
  { code: '9997', name: '퀵배송' },
  { code: '9998', name: '당일배송' },
] as const